key:
  - sequence: '&'
    increment: 1
    controller: 3

  - sequence: 'a'
    increment: -1
    controller: 3

  - sequence: 'é'
    increment: 1
    controller: 9

  - sequence: 'z'
    increment: -1
    controller: 9

  - sequence: '"'
    increment: 1
    controller: 14

  - sequence: 'e'
    increment: -1
    controller: 14

  - sequence: "'"
    increment: 1
    controller: 15

  - sequence: 'r'
    increment: -1
    controller: 15

  - sequence: '('
    increment: 1
    controller: 22

  - sequence: 't'
    increment: -1
    controller: 22

  - sequence: '-'
    increment: 1
    controller: 23

  - sequence: 'y'
    increment: -1
    controller: 23

  - sequence: 'è'
    increment: 1
    controller: 24

  - sequence: 'u'
    increment: -1
    controller: 24

  - sequence: '_'
    increment: 1
    controller: 25

  - sequence: 'i'
    increment: -1
    controller: 25

  - sequence: 'ç'
    increment: 1
    controller: 26

  - sequence: 'o'
    increment: -1
    controller: 26

  - sequence: 'à'
    increment: 1
    controller: 27

  - sequence: 'p'
    increment: -1
    controller: 27

  - sequence: 'q'
    increment: 1
    controller: 28

  - sequence: 'w'
    increment: -1
    controller: 28

  - sequence: 's'
    increment: 1
    controller: 29

  - sequence: 'x'
    increment: -1
    controller: 29

  - sequence: 'd'
    increment: 1
    controller: 30

  - sequence: 'c'
    increment: -1
    controller: 31

  - sequence: 'f'
    increment: 1
    controller: 35

  - sequence: 'v'
    increment: -1
    controller: 35

  - sequence: 'g'
    increment: 1
    controller: 41

  - sequence: 'b'
    increment: -1
    controller: 41

  - sequence: 'h'
    increment: 1
    controller: 46

  - sequence: 'n'
    increment: -1
    controller: 46

  - sequence: 'j'
    increment: 1
    controller: 47

  - sequence: ','
    increment: -1
    controller: 47

  - sequence: 'k'
    increment: 1
    controller: 52

  - sequence: ';'
    increment: -1
    controller: 52

  - sequence: 'l'
    increment: 1
    controller: 53

  - sequence: ':'
    increment: -1
    controller: 53

  - sequence: 'm'
    increment: 1
    controller: 54

  - sequence: '!'
    increment: -1
    controller: 54
