key:
  # Track solo button & Track arm button
  - sequence: '&'
    type: digital
    controller: 57
    channel: 0

  - sequence: 'a'
    type: digital
    controller: 58
    channel: 0

  - sequence: 'é'
    type: digital
    controller: 59
    channel: 0

  - sequence: 'z'
    type: digital
    controller: 60
    channel: 0

  - sequence: '"'
    type: digital
    controller: 61
    channel: 0

  - sequence: 'e'
    type: digital
    controller: 62
    channel: 0

  - sequence: "'"
    type: digital
    controller: 63
    channel: 0

  - sequence: 'r'
    type: digital
    controller: 85
    channel: 0

  - sequence: '('
    type: digital
    controller: 86
    channel: 0

  - sequence: 't'
    type: digital
    controller: 87
    channel: 0

  - sequence: '-'
    type: digital
    controller: 88
    channel: 0

  - sequence: 'y'
    type: digital
    controller: 89
    channel: 0

  - sequence: 'è'
    type: digital
    controller: 90
    channel: 0

  - sequence: 'u'
    type: digital
    controller: 102
    channel: 0

  - sequence: '_'
    type: digital
    controller: 103
    channel: 0

  - sequence: 'i'
    type: digital
    controller: 104
    channel: 0

  # Volume slider
  - sequence: 'q'
    type: analog
    increment: 1
    controller: 28
    channel: 0

  - sequence: 'w'
    type: analog
    increment: -1
    controller: 28
    channel: 0

  - sequence: 's'
    type: analog
    increment: 1
    controller: 29
    channel: 0

  - sequence: 'x'
    type: analog
    increment: -1
    controller: 29
    channel: 0

  - sequence: 'd'
    type: analog
    increment: 1
    controller: 30
    channel: 0

  - sequence: 'c'
    type: analog
    increment: -1
    controller: 31
    channel: 0

  - sequence: 'f'
    type: analog
    increment: 1
    controller: 35
    channel: 0

  - sequence: 'v'
    type: analog
    increment: -1
    controller: 35
    channel: 0

  - sequence: 'g'
    type: analog
    increment: 1
    controller: 41
    channel: 0

  - sequence: 'b'
    type: analog
    increment: -1
    controller: 41
    channel: 0

  - sequence: 'h'
    type: analog
    increment: 1
    controller: 46
    channel: 0

  - sequence: 'n'
    type: analog
    increment: -1
    controller: 46
    channel: 0

  - sequence: 'j'
    type: analog
    increment: 1
    controller: 47
    channel: 0

  - sequence: ','
    type: analog
    increment: -1
    controller: 47
    channel: 0

  - sequence: 'k'
    type: analog
    increment: 1
    controller: 52
    channel: 0

  - sequence: ';'
    type: analog
    increment: -1
    controller: 52
    channel: 0

  - sequence: 'l'
    type: analog
    increment: 1
    controller: 53
    channel: 0

  - sequence: ':'
    type: analog
    increment: -1
    controller: 53
    channel: 0

  - sequence: 'm'
    type: analog
    increment: 1
    controller: 54
    channel: 0

  - sequence: '!'
    type: analog
    increment: -1
    controller: 54
    channel: 0

  # Transport play button and stop button
  - sequence: ' '
    type: digital
    controller:
      cycle:
        - 55
        - 56
    channel: 0

    # Right arrow
  - sequence: '\u001b[C'
    type: digital
    controller: 105

    # Left arrow
  - sequence: '\u001b[D'
    type: digital
    controller: 106

    # up arrow
  - sequence: '\u001b[A'
    type: digital
    controller: 107

    # down arrow
  - sequence: '\u001b[B'
    type: digital
    controller: 108
